id: b56ec33b9c074f42ad4e0187de265b79
initial_creation_type: ocr
source_metadata:
  volumes:
    41d7c7161f444a5abb06429b73895ded:
      base_file: v078.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1433
      volume_number: 79
